### ISSUE TITLE
[Question] Extracão dos dados e cálculo

### ISSUE THREAD

**Issue by dcardosos** [denis-or/graficos#1]
Olá Denis, espero que esteja tudo certo contigo! 

Achei incrível esse gráfico que você fez e coincidiu, em partes, com um artigo sobre mortalidade materna que estou tentando reproduzir para a Iniciação Científica. Por isso, fiquei na dúvida de como você montou esse arquivo RDS. 

https://github.com/denis-or/graficos/blob/2b685002d10164f9e71655c14ad6c23f873a8af7/grafico_excesso_obito_2000_2021.R#L7

Você utilizou o SINASC e o SIM? Foi uma simples contagem de linhas por mês? 

Obrigado!

**Comment by denis-or** [comment]
Oi Douglas.

Bacana que gostou.

> Por isso, fiquei na dúvida de como você montou esse arquivo RDS.

Então, os dados do gráfico que mencionou são do SIM. Os dados no rds são do SIM e do SINASC mesmo. Para pegar os dados dos anos de 2000 a 2020, eu usei o tabulador do Datasus, o Tabnet (https://datasus.saude.gov.br/informacoes-de-saude-tabnet/). Então já coletei agregado por mês. O ano de 2021, eu peguei o arquivo preliminar com os dados até outubro (mas estou usando até agosto, porque setembro e outubro tem poucas observações). Neste último sim: agrupei por mês, contei e anexei aos outros anos fazendo uma base única. 

Para os anos de 2020 e 2021 os dados podem sofrer alguma alteração. Então a data da coleta que usei de referência foi fevereiro de 2022. Ou seja, até esta data, o rds é o que tem de mais atualizado, digamos assim.

**Comment by dcardosos** [comment]
Muito obrigado Denis, eu estava tentando usar o `basedosdados` e apesar de as variáveis estarem todas lá, acabei me confundindo bastante no que o artigo pedia, e percebi que o que está no artigo está igualzinho no Tabnet, facilitou!

Obrigado pelos esclarecimentos!
